### ISSUE TITLE
Include in JMRI distributions?

### ISSUE THREAD

**Issue by bobjacobsen** [lucadentella/jmri-cmdmapper#1]
Very nice script!  Would it be OK if I included it in the JMRI distribution, with a link back to this project?

Thanks for considering it.

**Comment by lucadentella** [comment]
Hi Bob! Absolutely yes, I'd be honored!
Thanks

**Comment by bobjacobsen** [comment]
Thanks!  This is now JMRI/JMRI#9734, should be merged a day or two.

**Comment by lucadentella** [comment]
Thanks, issue merged
